services:
  zookeeper:
    image: wurstmeister/zookeeper
    volumes:
      - zookeeper-data:/data
    networks:
      - service
  kafka:
    image: wurstmeister/kafka
    command: sh -c "rm -f ./kafka/meta.properties && start-kafka.sh"
    restart: always
    ports:
      - "9092"
    environment:
      KAFKA_CREATE_TOPICS: "events:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: kafka # docker-machine ip
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/kafka:/kafka
    depends_on:
      - "zookeeper"
    networks:
      - service
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: andrew
      MYSQL_PASSWORD: Kasavior47@
      MYSQL_DATABASE: storage
      TZ: America/Vancouver
    ports:
      - "3306"
    volumes:
      - ./data/database:/var/lib/mysql
    networks:
      - service

  receiver:
    restart: always
    build:
      context: receiver
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    volumes:
      - ./config/receiver:/app/config/receiver
      - ./logs/receiver:/app/logs/receiver
    networks:
      - service
  storage:
    restart: always
    build:
      context: storage
      dockerfile: Dockerfile
    ports:
      - "8090"
    depends_on:
      - kafka
      - db
    volumes:
      - ./config/storage:/app/config/storage
      - ./logs/storage:/app/logs/storage
    networks:
      - service
  processing:
    build:
      context: processing
      dockerfile: Dockerfile
    ports:
      - "8100:8100"
    depends_on:
      - storage
    volumes:
      - ./config/processing:/app/config/processing
      - ./logs/processing:/app/logs/processing
      - ./data/processing:/app/data/processing
    environment:
      - TZ=America/Vancouver
    networks:
      - service
  analyzer:
    build:
      context: analyzer
      dockerfile: Dockerfile
    ports:
      - "8200:8200"
    depends_on:
      - kafka
    volumes:
      - ./config/analyzer:/app/config/analyzer
      - ./logs/analyzer:/app/logs/analyzer
    networks:
      - service

volumes:
  zookeeper-data:
networks:
  service:
    driver: bridge