services:
  zookeeper:
    image: wurstmeister/zookeeper
    volumes:
      - zookeeper-data:/data
    networks:
      - service
  kafka:
    image: wurstmeister/kafka
    command: sh -c "rm -f ./kafka/meta.properties && start-kafka.sh"
    restart: always
    environment:
      KAFKA_CREATE_TOPICS: "events:1:1" # topic:partition:replicas
      KAFKA_ADVERTISED_HOST_NAME: kafka # docker-machine ip
      KAFKA_LISTENERS: INSIDE://:29092,OUTSIDE://:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:29092,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka
      TZ: America/Vancouver
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/kafka:/kafka
    depends_on:
      - "zookeeper"
    networks:
      - service
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: andrew
      MYSQL_PASSWORD: Kasavior47@
      MYSQL_DATABASE: storage
      TZ: America/Vancouver
    volumes:
      - ./data/database:/var/lib/mysql
    networks:
      - service

  receiver:
    restart: always
    deploy:
      replicas: 3
    build:
      context: receiver
      dockerfile: Dockerfile
    depends_on:
      - kafka
    volumes:
      - ./config/receiver:/app/config/receiver
      - ./logs/receiver:/app/logs/receiver
    networks:
      - service
  storage:
    restart: always
    build:
      context: storage
      dockerfile: Dockerfile
    depends_on:
      - kafka
      - db
    volumes:
      - ./config/storage:/app/config/storage
      - ./logs/storage:/app/logs/storage
    networks:
      - service
  processing:
    build:
      context: processing
      dockerfile: Dockerfile
    depends_on:
      - storage
    volumes:
      - ./config/processing:/app/config/processing
      - ./logs/processing:/app/logs/processing
      - ./data/processing:/app/data/processing
    environment:
      - TZ=America/Vancouver
      - CORS_ALLOW_ALL=no
    networks:
      - service
  analyzer:
    build:
      context: analyzer
      dockerfile: Dockerfile
    depends_on:
      - kafka
    volumes:
      - ./config/analyzer:/app/config/analyzer
      - ./logs/analyzer:/app/logs/analyzer
    environment:
      - CORS_ALLOW_ALL=no
    networks:
      - service

  dashboard:
    build:
      context: dashboard
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - receiver
      - storage
      - processing
      - analyzer
      - consistency-check
      - anomaly-detector
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - service

  consistency-check:
    build:
      context: consistency_check
      dockerfile: Dockerfile
    depends_on:
      - storage
      - processing
      - analyzer
    volumes:
      - ./config/consistency_check:/app/config/consistency_check
      - ./logs/consistency_check:/app/logs/consistency_check
      - ./data/consistency_check:/app/data/consistency_check
    networks:
      - service

  anomaly-detector:
    build:
      context: anomaly_detector
      dockerfile: Dockerfile
    depends_on:
      - kafka
    volumes:
      - ./config/anomaly_detector:/app/config/anomaly_detector
      - ./logs/anomaly_detector:/app/logs/anomaly_detector
      - ./data/anomaly_detector:/app/data/anomaly_detector
    networks:
      - service

volumes:
  zookeeper-data:
networks:
  service:
    driver: bridge