openapi: 3.0.0
info:
  version: 1.0.0
  title: Bulkup
  description: The software allows users to add the data of their workout sessions and diets
paths: 
  /bulkup/workout:
    # post:
    #   summary: Add the data of a workout session
    #   description: Endpoint to add the data of a user's workout session
    #   operationId: app.add_workout
    #   requestBody:
    #     description: Workout session data to be added
    #     content:
    #       application/json:
    #         schema: 
    #           $ref: '#/components/schemas/Workout'
    #   responses:
    #     "201": 
    #       description: Data added
    #     "400": 
    #       description: Invalid request
    get:
      tags:
        - devices
      summary: Get new workout data
      operationId: app.get_workout_data
      description: Get workout data added after a timestamp
      parameters:
        - name: start_timestamp
          in: query
          description: Limit the number of data returned
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
        - name: end_timestamp
          in: query
          description: Limit the number of data returned
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
      responses:
        "200":
          description: Successfully return a list of workout events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Workout'
  /bulkup/diet:
    # post:
    #   summary: Add the data of a diet
    #   description: Endpoint to add the data of a user's diet
    #   operationId: app.add_diet
    #   requestBody:
    #     description: Diet data to be added
    #     content:
    #       application/json:
    #         schema:
    #           $ref: '#/components/schemas/Diet'
    #   responses:
    #     "201": 
    #       description: Data added
    #     "400": 
    #       description: Invalid request
    get:
      tags:
        - devices
      summary: Get new diet data
      operationId: app.get_diet_data
      description: Get diet data added after a timestamp
      parameters:
        - name: start_timestamp
          in: query
          description: Limit the number of data returned
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
        - name: end_timestamp
          in: query
          description: Limit the number of data returned
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
      responses:
        "200":
          description: Successfully return a list of diet events
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Diet'
  /record-count:
    get:
      summary: Retrieve the num of rows for each event
      operationId: app.count_records
      responses:
        "200":
          description: Successfully count the num of records for each event
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: "#/components/schemas/CountingRows"
  /workout-id:
    get:
      summary: Retrieve ids for workout
      operationId: app.get_workout_ids
      responses:
        "200":
          description: Successfully retrieve ids for workout
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/WorkoutIds"
  /diet-id:
    get:
      summary: Retrieve ids for diet
      operationId: app.get_diet_ids
      responses:
        "200":
          description: Successfully retrieve ids for diet
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DietIds"
          
components:
  schemas:
    Workout:
      required: 
        - weight_lifted
        - duration
        - timestamp
        - trace_id
      type: object
      properties:
        workout_id:
          type: string
          description: Unique identifier for the workout session
          readOnly: true
        weight_lifted:
          type: integer
          description: Total weight lifted during the workout session
          example: 16328
        duration:
          type: integer
          description: Duration of the workout session
          example: 73
        timestamp:
          type: string
          description: Timestamp of the workout session
          format: date-time
          example: 2025-01-09T01:00:00Z
        date_created:
          type: string
          format: date-time
          example: 2025-01-09T01:00:00Z
        trace_id:
          type: string
          description: Unique identifier to track events
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
      additionalProperties: false
    Diet:
      required:
        - carb
        - protein
        - veg
        - calorie_intake
        - timestamp
        - trace_id
      type: object
      properties:
        diet_id:
          type: string
          description: Unique identifier for the diet
          readOnly: true
        carb:
          type: string
          description: Main carb source in the meal
          example: rice
        protein:
          type: string
          description: Main protein source in the meal
          example: chicken breast
        veg:
          type: string
          description: Main vegetable included in the meal
          example: broccoli
        calorie_intake:
          type: integer
          description: Total calorie intake of the meal
          example: 1000
        timestamp:
          type: string
          description: Timestamp of the meal
          format: date-time
          example: 2025-01-09T01:00:00Z
        date_created:
          type: string
          format: date-time
          example: 2025-01-09T01:00:00Z
        trace_id:
          type: string
          description: Unique identifier to track events
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
      additionalProperties: false
    CountingRows:
      required:
        - workout_row_count
        - diet_row_count
      properties:
        workout_row_count:
          type: integer
          example: 1
        diet_row_count:
          type: integer
          example: 1
    WorkoutIds:
      type: array
      items:
        type: object
        required:
          - event_id
          - trace_id
        properties:
          event_id:
            type: string
          trace_id:
            type: string
            format: uuid
            example: d290f1ee-6c54-4b01-90e6-d701748f0851
    DietIds:
      type: array
      items:
        type: object
        required:
          - event_id
          - trace_id
        properties:
          event_id:
            type: string
          trace_id:
            type: string
            format: uuid
            example: d290f1ee-6c54-4b01-90e6-d701748f0851