services:
  db:
    image: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: andrew
      MYSQL_PASSWORD: Kasavior47@
      MYSQL_DATABASE: storage
      TZ: America/Vancouver
    ports:
      - 3306:3306